config/routes.rb
Rails.application.routes.draw do
  get 'new', to: 'games#new', as: :new
  post 'score', to: 'games#score', as: :score
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'open-uri'
require 'json'

DICT_API_URL = 'https://wagon-dictionary.herokuapp.com/'

class GamesController < ApplicationController

  def new
    set_cache_headers
    @letters = random_letters(10)
  end

  def score
    @letters = params[:letters].chars
    @word    = params[:word].strip
    if !contains_letters?(@word.chars, @letters.dup)
      @error = :word_not_from_grid
    elsif !valid_word?(@word)
      @error = :word_not_valid
    end
    calculate_score(@word)
  end

  private

  def set_cache_headers
    response.headers["Cache-Control"] = "no-cache, no-store"
  end

  def valid_word?(word)
    url = DICT_API_URL + word
    response = open(url).read
    json = JSON.parse(response)
    json['found']
  end

  def contains_letters?(needle, haystack)
    # binding.pry
    needle.each do |letter|
      return false unless haystack.include? letter

      # delete only the first instance of the letter
      haystack.delete_at(haystack.index(letter))
    end
    true
  end

  def random_letters(count)
    letters = []
    alphabet = 'abcdefghijklmnopqrstuvwxyz'.chars
    count.times do
      letters.push(alphabet.sample)
    end
    letters
  end

  def calculate_score(word)
    @current_score = @error.nil? ? word.length : 0
    @total_score = session[:total_score] || 0
    @total_score += @current_score
    session[:total_score] = @total_score
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<div class="container m-4">
  <h1>New Game</h1>

  <div class="letters mb-4">
    <% @letters.each do |letter| %>
    <div class="letter"><%= letter.capitalize %></div>
    <% end %>
  </div>


  <form action="<%= score_path %>" method="post">
    <div class="form-group">
      <label for="word">What is the longest word you can find?</label>
      <div class="form-row">
        <div class="col">
          <div class="input-group">
            <input type="text" name="word" class="form-control" required>
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <%= hidden_field_tag 'letters', @letters.join %>
            <div class="input-group-append">
              <input type="submit" value="Play">
            </div>
          </div>
        </div>
      </div>
    </div>
  </form>
</div>

app/views/games/score.html.erb
<div class="container m-4">
  <h1>Score</h1>
  <% if @error == :word_not_from_grid %>
  <p>Sorry, but <strong><%= @word.upcase %></strong>
   can't be built out of <%= @letters.join(', ').upcase %>.</p>
   <% elsif @error == :word_not_valid %>
   <p>Sorry, but <strong><%= @word.upcase %></strong>
   doesn't seem to be an English word.</p>
   <% else %>
   <p><strong>Congratulations!</strong> <%= @word.upcase %>
   is a valid English word!</p>
   <% end %>
   <div class="scores">
    <p>Your score for this round: <span class="score score-current"><%= @current_score %></span></p>
    <p>Your total score: <span class="score score-total"><%= @total_score %></span></p>
  </div>

  <%= link_to 'Play again', new_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Longest Word Game</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>